server:
  port: 8080

spring:
  application:
    name: stockpulse-backend

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stockpulse-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:demo}
      chat:
        options:
          model: gpt-3.5-turbo
